services:
  - type: web
    name: ray-group-score
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:server
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN
        sync: false
      - key: STRIPE_CURRENCY
        value: nzd
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_MERCHANT_ACCOUNT_ID
        sync: false
      - key: STRIPE_SUCCESS_URL
        sync: false
      - key: STRIPE_CANCEL_URL
        sync: false
