import { useState } from 'react';
import { ActivityIndicator, Platform, Pressable, SafeAreaView, StatusBar, StyleSheet, Text, View } from 'react-native';

export function GenerateLobbyCodeScreen({ isLoading, onBack, onGenerate }: { isLoading: boolean; onBack: () => void; onGenerate: () => void }) {
  const [difficulty, setDifficulty] = useState<string | null>(null);
  const isWeb = Platform.OS === 'web';
  return <SafeAreaView style={[styles.safeArea, isWeb && styles.webCanvas]}><StatusBar backgroundColor="#AAB7E9" barStyle="dark-content" /><View style={[styles.content, isWeb && styles.phoneFrame]}><View><Pressable onPress={onBack}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.headline}>set your</Text><Text style={styles.tagline}>game <Text style={styles.accent}>difficulty</Text></Text><Text style={styles.label}>SELECT DIFFICULTY</Text><View style={styles.options}>{['Easy', 'Medium', 'Hard'].map((option) => <Pressable key={option} onPress={() => setDifficulty(option)} style={[styles.option, difficulty === option && styles.optionSelected]}><Text style={[styles.optionText, difficulty === option && styles.optionTextSelected]}>{option}</Text></Pressable>)}</View><View style={styles.shadow}><Pressable disabled={!difficulty || isLoading} onPress={onGenerate} style={[styles.button, (!difficulty || isLoading) && styles.buttonDisabled]}>{isLoading ? <ActivityIndicator color="#F5EFDA" /> : <Text style={[styles.buttonText, !difficulty && styles.buttonTextDisabled]}>GENERATE CODE</Text>}</Pressable></View></View><Text style={styles.hint}>Your lobby code will be ready to share next.</Text></View></SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { backgroundColor: '#AAB7E9', flex: 1 }, webCanvas: { backgroundColor: '#AAB7E9' }, phoneFrame: { alignSelf: 'center', borderColor: '#15121F', borderLeftWidth: 3, borderRightWidth: 3, maxWidth: '100%', minHeight: '100%', width: 390 }, content: { flex: 1, justifyContent: 'space-between', paddingBottom: 22, paddingHorizontal: 26, paddingTop: 52 }, back: { color: '#15121F', fontSize: 13, fontWeight: '800', marginBottom: 20 }, headline: { color: '#15121F', fontSize: 26, fontWeight: '800', lineHeight: 28 }, tagline: { color: '#15121F', fontSize: 26, fontWeight: '700', lineHeight: 28, marginBottom: 24 }, accent: { color: '#3E4AA0', fontWeight: '800' }, label: { color: '#15121F', fontSize: 11, fontWeight: '800', letterSpacing: 1.4, marginBottom: 8 }, options: { gap: 9, marginBottom: 22 }, option: { backgroundColor: '#F5EFDA', borderColor: '#15121F', borderRadius: 18, borderWidth: 2.5, paddingHorizontal: 18, paddingVertical: 16 }, optionSelected: { backgroundColor: '#3E4AA0' }, optionText: { color: '#15121F', fontSize: 14, fontWeight: '800', textTransform: 'uppercase' }, optionTextSelected: { color: '#F5EFDA' }, shadow: { backgroundColor: '#3E4AA0', borderRadius: 20, marginRight: -5, paddingBottom: 5, paddingRight: 5 }, button: { alignItems: 'center', backgroundColor: '#15121F', borderColor: '#15121F', borderRadius: 20, borderWidth: 3, justifyContent: 'center', minHeight: 62 }, buttonDisabled: { backgroundColor: 'rgba(21,18,31,0.15)' }, buttonText: { color: '#F5EFDA', fontSize: 15, fontWeight: '800', letterSpacing: 0.45 }, buttonTextDisabled: { color: 'rgba(21,18,31,0.4)' }, hint: { color: 'rgba(21,18,31,0.55)', fontSize: 12, fontWeight: '700', letterSpacing: 0.5 },
});
