import { Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import type { GroupMember } from './GroupScoreScreen';

export type GroupHistory = { id: string; name: string; lastSession: string; duration: string; pos: string; members: GroupMember[] };

export function HistoryScreen({ groups, profileName, onBack, onOpenGroup, onOpenMap }: { groups: GroupHistory[]; profileName: string; onBack: () => void; onOpenGroup: (group: GroupHistory) => void; onOpenMap: () => void }) {
  return <SafeAreaView style={styles.safeArea}><StatusBar barStyle="dark-content" backgroundColor="#AAB7E9" /><View style={styles.header}><Pressable onPress={onBack} hitSlop={12} style={styles.headerSide}><Text numberOfLines={1} style={styles.back}>‹ Lobby</Text></Pressable><Text numberOfLines={1} style={styles.headerTitle}>HISTORY</Text><View style={styles.headerSide} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text adjustsFontSizeToFit minimumFontScale={0.8} numberOfLines={1} style={styles.title}>{profileName}'s <Text style={styles.accent}>groups</Text></Text><Text style={styles.subtitle}>Review the latest phone-lift scores from every group.</Text><View style={styles.list}><Pressable onPress={onOpenMap} style={({ pressed }) => [styles.card, styles.mapCard, pressed && styles.pressed]}><View style={styles.cardHeader}><Text style={styles.groupName}>View all locations</Text><Text style={styles.chevron}>Map</Text></View><Text style={styles.session}>Browse every saved session on the map.</Text></Pressable>{groups.map((group) => <Pressable key={group.id} onPress={() => onOpenGroup(group)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.cardHeader}><Text numberOfLines={1} style={styles.groupName}>{group.name}</Text><Text style={styles.chevron}>›</Text></View><Text style={styles.session}>{group.lastSession} · {group.duration}</Text><View style={styles.summary}><Text style={styles.members}>{group.members.length} members</Text><Text style={styles.average}>100% allocated</Text></View></Pressable>)}</View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#EFEAF9' }, header: { alignItems: 'center', backgroundColor: '#EFEAF9', borderBottomColor: '#15121F', borderBottomWidth: 2, flexDirection: 'row', justifyContent: 'space-between', minHeight: 64, paddingHorizontal: 16 }, headerSide: { flex: 1, minWidth: 0 }, back: { color: '#3E4AA0', fontSize: 15, fontWeight: '800' }, headerTitle: { color: '#15121F', flexShrink: 0, fontSize: 12, fontWeight: '800', letterSpacing: 1.5, textAlign: 'center' }, content: { padding: 20, paddingBottom: 40 }, title: { color: '#15121F', fontSize: 30, fontWeight: '800' }, accent: { color: '#3E4AA0' }, subtitle: { color: 'rgba(21,18,31,0.62)', fontSize: 14, fontWeight: '600', lineHeight: 21, marginTop: 7 }, list: { gap: 14, marginTop: 26 }, card: { backgroundColor: '#F5EFDA', borderColor: '#15121F', borderRadius: 18, borderWidth: 2.5, padding: 16 }, mapCard: { backgroundColor: '#DCE4FF' }, pressed: { opacity: 0.65 }, cardHeader: { alignItems: 'center', flexDirection: 'row', gap: 8, justifyContent: 'space-between' }, groupName: { color: '#15121F', flex: 1, minWidth: 0, fontSize: 19, fontWeight: '800' }, chevron: { color: '#3E4AA0', flexShrink: 0, fontSize: 16, fontWeight: '800' }, session: { color: 'rgba(21,18,31,0.58)', flexShrink: 1, fontSize: 13, fontWeight: '600', lineHeight: 18, marginTop: 4 }, summary: { alignItems: 'center', borderTopColor: 'rgba(21,18,31,0.2)', borderTopWidth: 1.5, flexDirection: 'row', flexWrap: 'wrap', gap: 8, justifyContent: 'space-between', marginTop: 15, paddingTop: 14 }, members: { color: 'rgba(21,18,31,0.65)', flexShrink: 1, fontSize: 13, fontWeight: '700' }, average: { color: '#3E4AA0', flexShrink: 0, fontSize: 13, fontWeight: '800' },
});
