import { Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import type { GroupMember } from './GroupScoreScreen';

export type GroupHistory = { id: string; name: string; lastSession: string; duration: string; pos: string; members: GroupMember[] };
const PLACEHOLDER_MEAL_TOTAL = 72;

export function HistoryScreen({ groups, profileName, onBack, onOpenGroup }: { groups: GroupHistory[]; profileName: string; onBack: () => void; onOpenGroup: (group: GroupHistory) => void; onOpenMap: () => void }) {
  return <SafeAreaView style={styles.safeArea}><StatusBar barStyle="dark-content" backgroundColor="#AAB7E9" /><View style={styles.header}><Pressable onPress={onBack} hitSlop={12} style={styles.headerSide}><Text style={styles.back}>‹ Lobby</Text></Pressable><Text style={styles.headerTitle}>HISTORY</Text><View style={styles.headerSide} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>{profileName}'s <Text style={styles.accent}>history</Text></Text><Text style={styles.subtitle}>Review your past stacks and what phone use cost you.</Text><View style={styles.list}>{groups.map((group) => { const member = group.members.find((item) => item.name === profileName); const equal = PLACEHOLDER_MEAL_TOTAL / group.members.length; const paid = PLACEHOLDER_MEAL_TOTAL * (member?.percentage ?? 0) / 100; const difference = paid - equal; const isMore = difference > 0.005; return <Pressable key={group.id} onPress={() => onOpenGroup(group)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.cardHeader}><Text numberOfLines={1} style={styles.groupName}>{group.name}</Text><Text style={styles.chevron}>›</Text></View><Text style={styles.session}>{group.lastSession} · {group.duration}</Text><View style={styles.summary}><Text style={styles.members}>{group.members.length} people</Text><Text style={[styles.difference, isMore ? styles.more : styles.less]}>{isMore ? `+$${difference.toFixed(2)} more` : `$${Math.abs(difference).toFixed(2)} less`} than equal split</Text></View></Pressable>; })}</View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#EFEAF9' }, header: { alignItems: 'center', borderBottomColor: '#15121F', borderBottomWidth: 2, flexDirection: 'row', justifyContent: 'space-between', minHeight: 64, paddingHorizontal: 16 }, headerSide: { flex: 1 }, back: { color: '#3E4AA0', fontSize: 15, fontWeight: '800' }, headerTitle: { color: '#15121F', fontSize: 12, fontWeight: '800', letterSpacing: 1.5 }, content: { padding: 20, paddingBottom: 40 }, title: { color: '#15121F', fontSize: 30, fontWeight: '800' }, accent: { color: '#3E4AA0' }, subtitle: { color: 'rgba(21,18,31,.62)', fontSize: 14, fontWeight: '600', lineHeight: 21, marginTop: 7 }, list: { gap: 14, marginTop: 26 }, card: { backgroundColor: '#F5EFDA', borderColor: '#15121F', borderRadius: 18, borderWidth: 2.5, padding: 16 }, pressed: { opacity: .65 }, cardHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, groupName: { color: '#15121F', flex: 1, fontSize: 19, fontWeight: '800' }, chevron: { color: '#3E4AA0', fontSize: 20, fontWeight: '800' }, session: { color: 'rgba(21,18,31,.58)', fontSize: 13, fontWeight: '600', marginTop: 4 }, summary: { alignItems: 'center', borderTopColor: 'rgba(21,18,31,.2)', borderTopWidth: 1.5, flexDirection: 'row', justifyContent: 'space-between', marginTop: 15, paddingTop: 14 }, members: { color: 'rgba(21,18,31,.65)', fontSize: 13, fontWeight: '700' }, difference: { fontSize: 12, fontVariant: ['tabular-nums'], fontWeight: '800' }, more: { color: '#D9705F' }, less: { color: '#237050' },
});
