import { ActivityIndicator, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import type { WaitingPlayer } from './LobbyWaitingScreen';

type Props = { lobbyCode: string; lobbyName: string; players: WaitingPlayer[]; hostUserId: string; isStarting: boolean; error?: string | null; onBack: () => void; onStart: () => void };

export function HostWaitingScreen({ lobbyCode, players, hostUserId, isStarting, error, onBack, onStart }: Props) {
  const isWeb = Platform.OS === 'web';
  return <SafeAreaView style={[styles.safeArea, isWeb && styles.webCanvas]}><StatusBar barStyle="dark-content" backgroundColor="#AAB7E9" /><ScrollView contentContainerStyle={[styles.content, isWeb && styles.phoneFrame]} showsVerticalScrollIndicator={false}><View><Pressable onPress={onBack}><Text style={styles.back}>← Back</Text></Pressable><Text style={styles.headline}>start when</Text><Text style={styles.tagline}>everyone&apos;s <Text style={styles.accent}>joined</Text></Text><Text style={styles.lobbyCode}>LOBBY CODE: {lobbyCode}</Text><Text style={styles.fieldLabel}>PLAYERS JOINED ({players.length})</Text>{players.map((player) => <View key={player.userId} style={styles.playerRow}><View style={styles.avatar} /><Text numberOfLines={1} style={styles.playerName}>{player.name}</Text>{player.userId === hostUserId ? <Text style={styles.hostBadge}>HOST</Text> : null}</View>)}{error ? <Text style={styles.error}>{error}</Text> : null}</View><View style={styles.buttonShadow}><Pressable accessibilityRole="button" disabled={isStarting} onPress={onStart} style={({ pressed }) => [styles.startButton, pressed && styles.startButtonPressed]}>{isStarting ? <ActivityIndicator color="#F5EFDA" /> : <Text style={styles.startText}>START SESSION</Text>}</Pressable></View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { backgroundColor: '#AAB7E9', flex: 1 }, webCanvas: { backgroundColor: '#AAB7E9' }, phoneFrame: { alignSelf: 'center', borderColor: '#15121F', borderLeftWidth: 3, borderRightWidth: 3, maxWidth: '100%', minHeight: '100%', width: 390 }, content: { flexGrow: 1, justifyContent: 'space-between', paddingBottom: 22, paddingHorizontal: 26, paddingTop: 52 }, back: { color: '#15121F', fontSize: 13, fontWeight: '800', marginBottom: 20 }, headline: { color: '#15121F', fontSize: 26, fontWeight: '800', lineHeight: 28 }, tagline: { color: '#15121F', fontSize: 26, fontWeight: '700', lineHeight: 28, marginBottom: 22 }, accent: { color: '#3E4AA0', fontWeight: '800' }, lobbyCode: { color: '#3E4AA0', fontSize: 12, fontWeight: '800', letterSpacing: 1.2, marginBottom: 16 }, fieldLabel: { color: '#15121F', fontSize: 11, fontWeight: '700', letterSpacing: 1.3, marginBottom: 8 }, playerRow: { alignItems: 'center', backgroundColor: '#F5EFDA', borderColor: '#15121F', borderRadius: 16, borderWidth: 2.5, flexDirection: 'row', gap: 12, marginBottom: 10, minHeight: 58, paddingHorizontal: 14, paddingVertical: 10 }, avatar: { backgroundColor: '#AAB7E9', borderColor: '#15121F', borderRadius: 17, borderWidth: 2, flexShrink: 0, height: 34, width: 34 }, playerName: { color: '#15121F', flex: 1, fontSize: 13.5, fontWeight: '700', minWidth: 0 }, hostBadge: { backgroundColor: '#15121F', borderRadius: 8, color: '#F5EFDA', flexShrink: 0, fontSize: 8, fontWeight: '700', letterSpacing: 0.65, overflow: 'hidden', paddingHorizontal: 6, paddingVertical: 3 }, error: { color: '#761C2C', fontSize: 12, fontWeight: '700', marginTop: 8 }, buttonShadow: { backgroundColor: '#3E4AA0', borderRadius: 20, marginRight: -5, paddingBottom: 5, paddingRight: 5 }, startButton: { alignItems: 'center', backgroundColor: '#15121F', borderColor: '#15121F', borderRadius: 20, borderWidth: 3, justifyContent: 'center', minHeight: 62, paddingHorizontal: 18, paddingVertical: 17 }, startButtonPressed: { opacity: 0.86, transform: [{ translateX: 2 }, { translateY: 2 }] }, startText: { color: '#F5EFDA', fontSize: 15, fontWeight: '800', letterSpacing: 0.45 },
});
