import { Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import type { FinalBillPlayer } from './useStackLobby';

export function SessionSummaryScreen({ onHome, players }: { onHome: () => void; players: FinalBillPlayer[] }) {
  const isWeb = Platform.OS === 'web';
  const sortedPlayers = [...players].sort((a, b) => b.billPercent - a.billPercent);
  return <SafeAreaView style={styles.safeArea}><StatusBar backgroundColor="#AAB7E9" barStyle="dark-content" /><ScrollView contentContainerStyle={[styles.content, isWeb && styles.phoneFrame]}><Text style={styles.eyebrow}>SESSION COMPLETE</Text><Text style={styles.title}>final <Text style={styles.accent}>bill</Text></Text><Text style={styles.subtitle}>Here is everyone&apos;s final share.</Text><View style={styles.card}>{sortedPlayers.map((player, index) => <View key={player.userId} style={[styles.row, index === 0 && styles.winner]}><Text style={[styles.rank, index === 0 && styles.winnerText]}>#{index + 1}</Text><Text style={[styles.name, index === 0 && styles.winnerText]}>{player.displayName}</Text><Text style={[styles.percent, index === 0 && styles.winnerText]}>{Math.round(player.billPercent)}%</Text></View>)}</View><Pressable onPress={onHome} style={styles.homeButton}><Text style={styles.homeText}>RETURN HOME</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { backgroundColor: '#AAB7E9', flex: 1 }, content: { flexGrow: 1, gap: 18, padding: 26, paddingTop: 52 }, phoneFrame: { alignSelf: 'center', borderColor: '#15121F', borderLeftWidth: 3, borderRightWidth: 3, maxWidth: '100%', minHeight: '100%', width: 390 }, eyebrow: { color: 'rgba(21,18,31,0.6)', fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, title: { color: '#15121F', fontSize: 31, fontWeight: '800' }, accent: { color: '#3E4AA0' }, subtitle: { color: 'rgba(21,18,31,0.65)', fontSize: 14, fontWeight: '600', marginTop: -10 }, card: { backgroundColor: '#F5EFDA', borderColor: '#15121F', borderRadius: 20, borderWidth: 2.5, gap: 9, padding: 14 }, row: { alignItems: 'center', borderColor: '#15121F', borderRadius: 14, borderWidth: 2, flexDirection: 'row', gap: 12, paddingHorizontal: 13, paddingVertical: 14 }, winner: { backgroundColor: '#3E4AA0' }, rank: { color: '#3E4AA0', fontSize: 15, fontWeight: '800', width: 28 }, name: { color: '#15121F', flex: 1, fontSize: 16, fontWeight: '800' }, percent: { color: '#15121F', fontSize: 19, fontVariant: ['tabular-nums'], fontWeight: '800' }, winnerText: { color: '#F5EFDA' }, homeButton: { alignItems: 'center', backgroundColor: '#15121F', borderColor: '#15121F', borderRadius: 20, borderWidth: 3, marginTop: 'auto', minHeight: 62, justifyContent: 'center' }, homeText: { color: '#F5EFDA', fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
});
